PRODUCT_EVENT_GROUPS = {
    "bot_started": "user_lifecycle",
    "onboarding_started": "user_lifecycle",
    "onboarding_completed": "user_lifecycle",
    "language_selected": "user_lifecycle",
    "operation_started": "operations",
    "operation_created": "operations",
    "operation_failed": "operations",
    "operation_edited": "operations",
    "operation_deleted": "operations",
    "budget_creation_started": "budgets_limits",
    "budget_categories_selected": "budgets_limits",
    "budget_created": "budgets_limits",
    "budget_deleted": "budgets_limits",
    "limit_created": "budgets_limits",
    "limit_updated": "budgets_limits",
    "limit_deleted": "budgets_limits",
    "limit_threshold_reached": "budgets_limits",
    "category_created": "categories",
    "category_renamed": "categories",
    "reminder_created": "reminders_notifications",
    "reminder_deleted": "reminders_notifications",
    "notification_sent": "reminders_notifications",
    "notification_clicked": "reminders_notifications",
    "notification_converted": "reminders_notifications",
    "export_started": "export",
    "export_completed": "export",
    "export_failed": "export",
    "weekly_report_opened": "reports",
    "monthly_report_opened": "reports",
    "privacy_opened": "privacy",
    "financial_history_deleted": "privacy",
    "account_deleted": "privacy",
    "workspace_created": "workspaces",
    "workspace_joined": "workspaces",
    "workspace_join_rejected": "workspaces",
    "workspace_switched": "workspaces",
    "miniapp_opened": "miniapp",
    "screen_viewed": "miniapp",
    "form_started": "miniapp",
    "form_completed": "miniapp",
    "form_abandoned": "miniapp",
    "error_shown": "miniapp",
    "acquisition_payload_rejected": "attribution",
    "posthog_connection_test": "diagnostics",
    "challenge_screen_opened": "challenges",
    "challenge_assigned": "challenges",
    "challenge_progressed": "challenges",
    "challenge_completed": "challenges",
    "challenge_cta_opened": "challenges",
    "challenge_notification_sent": "challenges",
    "challenge_notification_skipped_quiet_hours": "challenges",
    "automatic_notification_deferred": "notifications",
    "automatic_notification_skipped_quiet_hours": "notifications",
    "automatic_notification_sent": "notifications",
    "quiet_hours_enabled": "settings",
    "quiet_hours_updated": "settings",
}

SECURITY_EVENTS = {
    "permission_denied",
    "foreign_workspace_access",
    "foreign_draft_access",
    "invalid_callback",
    "unknown_callback",
    "admin_command_denied",
    "group_join_rejected",
    "rate_limit_exceeded",
    "excessive_ocr_usage",
    "excessive_voice_usage",
    "excessive_exports",
    "operation_velocity_spike",
    "account_recreated_after_deletion",
}

API_FEATURES = {
    "voice_transcription",
    "receipt_ocr",
    "bank_screenshot_ocr",
    "categorization",
    "future_ai_assistant",
}
