PRODUCT_EVENT_GROUPS = {
    "bot_started": "user_lifecycle",
    "onboarding_started": "user_lifecycle",
    "onboarding_completed": "user_lifecycle",
    "language_selected": "user_lifecycle",
    "operation_started": "operations",
    "operation_created": "operations",
    "operation_failed": "operations",
    "operation_edited": "operations",
    "operation_deleted": "operations",
    "budget_creation_started": "budgets_limits",
    "budget_categories_selected": "budgets_limits",
    "budget_created": "budgets_limits",
    "budget_deleted": "budgets_limits",
    "limit_created": "budgets_limits",
    "limit_updated": "budgets_limits",
    "limit_deleted": "budgets_limits",
    "limit_threshold_reached": "budgets_limits",
    "category_created": "categories",
    "category_renamed": "categories",
    "reminder_created": "reminders_notifications",
    "reminder_deleted": "reminders_notifications",
    "notification_sent": "reminders_notifications",
    "notification_clicked": "reminders_notifications",
    "notification_converted": "reminders_notifications",
    "export_started": "export",
    "export_completed": "export",
    "export_failed": "export",
    "weekly_report_opened": "reports",
    "monthly_report_opened": "reports",
    "privacy_opened": "privacy",
    "financial_history_deleted": "privacy",
    "account_deleted": "privacy",
    "workspace_created": "workspaces",
    "workspace_joined": "workspaces",
    "workspace_join_rejected": "workspaces",
    "workspace_switched": "workspaces",
    "miniapp_opened": "miniapp",
    "screen_viewed": "miniapp",
    "form_started": "miniapp",
    "form_completed": "miniapp",
    "form_abandoned": "miniapp",
    "error_shown": "miniapp",
    "mini_app_opened": "miniapp",
    "mini_app_tab_opened": "miniapp",
    "mini_app_workspace_changed": "miniapp",
    "mini_app_period_changed": "miniapp",
    "mini_app_transaction_add_opened": "miniapp",
    "mini_app_transaction_created": "miniapp",
    "mini_app_transaction_edited": "miniapp",
    "mini_app_transaction_deleted": "miniapp",
    "mini_app_theme_changed": "miniapp",
    "mini_app_global_filter_opened": "miniapp",
    "mini_app_global_filter_applied": "miniapp",
    "mini_app_analytics_chart_filter_changed": "miniapp",
    "mini_app_analytics_grouping_changed": "miniapp",
    "mini_app_analytics_details_toggled": "miniapp",
    "mini_app_activity_calendar_opened": "miniapp",
    "mini_app_goal_created": "miniapp",
    "mini_app_goal_contribution_added": "miniapp",
    "mini_app_goal_plan_changed": "miniapp",
    "mini_app_budget_limit_created": "miniapp",
    "mini_app_budget_limit_updated": "miniapp",
    "mini_app_budget_limit_deleted": "miniapp",
    "mini_app_premium_opened": "miniapp",
    "mini_app_notification_setting_changed": "miniapp",
    "mini_app_export_opened": "miniapp",
    "mini_app_export_sent": "miniapp",
    "mini_app_category_created": "miniapp",
    "mini_app_category_renamed": "miniapp",
    "mini_app_category_deleted": "miniapp",
    "mini_app_home_challenge_opened": "miniapp",
    "mini_app_home_focus_opened": "miniapp",
    "mini_app_home_insight_opened": "miniapp",
    "insight_impression": "miniapp",
    "insight_opened": "miniapp",
    "insight_action_clicked": "miniapp",
    "insight_feedback": "miniapp",
    "mini_app_home_reminder_opened": "miniapp",
    "mini_app_challenge_carousel_changed": "miniapp",
    "mini_app_focus_carousel_changed": "miniapp",
    "mini_app_reminder_carousel_changed": "miniapp",
    "mini_app_plans_reminders_opened": "miniapp",
    "mini_app_reminder_opened": "miniapp",
    "mini_app_reminder_created": "miniapp",
    "mini_app_reminder_recorded": "miniapp",
    "mini_app_reminder_snoozed": "miniapp",
    "mini_app_reminder_updated": "miniapp",
    "mini_app_budget_opened": "miniapp",
    "mini_app_budget_created": "miniapp",
    "smart_planning_opened": "miniapp",
    "smart_planning_calculated": "miniapp",
    "smart_planning_applied": "miniapp",
    "smart_planning_warning_seen": "miniapp",
    "report_opened": "reports",
    "report_drilldown_opened": "reports",
    "report_export_requested": "reports",
    "mini_app_activity_opened": "miniapp",
    "mini_app_profile_section_opened": "miniapp",
    "mini_app_profile_setting_changed": "miniapp",
    "acquisition_payload_rejected": "attribution",
    "posthog_connection_test": "diagnostics",
    "challenge_screen_opened": "challenges",
    "challenge_assigned": "challenges",
    "challenge_progressed": "challenges",
    "challenge_completed": "challenges",
    "challenge_cta_opened": "challenges",
    "challenge_notification_sent": "challenges",
    "challenge_notification_skipped_quiet_hours": "challenges",
    "challenge_notifications_enabled": "settings",
    "challenge_notifications_disabled": "settings",
    "automatic_notification_deferred": "notifications",
    "automatic_notification_skipped_quiet_hours": "notifications",
    "automatic_notification_sent": "notifications",
    "quiet_hours_enabled": "settings",
    "quiet_hours_updated": "settings",
    "goal_screen_opened": "goals",
    "goal_creation_started": "goals",
    "goal_created": "goals",
    "goal_plan_created": "goals",
    "goal_plan_updated": "goals",
    "goal_contribution_added": "goals",
    "goal_withdrawal_added": "goals",
    "goal_progress_adjusted": "goals",
    "goal_reminders_enabled": "goals",
    "goal_reminders_disabled": "goals",
    "goal_reminder_sent": "goals",
    "goal_income_suggestion_shown": "goals",
    "goal_income_suggestion_accepted": "goals",
    "goal_income_suggestion_snoozed": "goals",
    "goal_income_suggestion_dismissed": "goals",
    "goal_achieved": "goals",
    "goal_paused": "goals",
    "goal_resumed": "goals",
    "goal_archived": "goals",
    "goal_restored": "goals",
    "goal_deleted": "goals",
    "goal_notifications_enabled": "settings",
    "goal_notifications_disabled": "settings",
}

SECURITY_EVENTS = {
    "permission_denied",
    "foreign_workspace_access",
    "foreign_draft_access",
    "invalid_callback",
    "unknown_callback",
    "admin_command_denied",
    "group_join_rejected",
    "rate_limit_exceeded",
    "excessive_ocr_usage",
    "excessive_voice_usage",
    "excessive_exports",
    "operation_velocity_spike",
    "account_recreated_after_deletion",
}

API_FEATURES = {
    "voice_transcription",
    "receipt_ocr",
    "bank_screenshot_ocr",
    "categorization",
    "future_ai_assistant",
}
